authors:
  szarkan:
    name: Серёжа
    description: Всекотец
    avatar: https://cravatar.eu/avatar/szarkan/400.png
    url: https://github.com/squidfunk
  bkke:
    name: Яна Симонец
    description: Всекот
    avatar: https://cravatar.eu/avatar/bykkake747/400.png
    url: https://github.com/alexvoss